spring:
    profiles:
        active: dev
    thymeleaf:
        cache: false
        prefix: file:src/main/resources/templates/  #directly serve from src folder instead of target
    resources:
        static-locations: file:src/main/resources/static/ #directly serve from src folder instead of target
        cache:
            period: 0
    mvc:
        static-path-pattern: /static/**

    #for /h2-console, xFrame  ##the default db url: jdbc:h2:mem:testdb
    h2:
        console:
            enabled: true

logging.level:
    g.t: TRACE
