version: '3'
services:
    elastichq:
        image: 'elastichq/elasticsearch-hq'
        container_name: elastichq
        ports:
            - 5000:5000
        networks:
            - esnet

    ## we can connect to elasticsearch by connecting to http://elasticsearch:9200 on HQ (http://localhost:5000)
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:7.8.1'
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
        volumes:
            - esdata1:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - esnet
    keycloak:
        image: 'quay.io/keycloak/keycloak:10.0.0'
        container_name: keycloak
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - KEYCLOAK_IMPORT=/tmp/test-realm.json
        volumes:
            - ../main-app/src/main/resources/keycloak/keycloak-export.json:/tmp/test-realm.json
        ports:
            - 8082:8080
        networks:
            - esnet
    activemq_artemis:
        image: 'vromero/activemq-artemis'
        container_name: activemqArtemis
        environment:
            - ARTEMIS_USERNAME=admin
            - ARTEMIS_PASSWORD=admin
        ports:
            - 8161:8161  # use this to login
            - 61616:61616
        networks:
                - esnet
volumes:
    esdata1:
        driver: local
networks:
    esnet:
        driver: bridge


#run using
#docker-compose -f docker-compose.yml up
# or just docker-compose up
