spring:
    profiles:
        active: dev
    thymeleaf:
        cache: false
        prefix: file:core/src/main/resources/templates/  #directly serve from src folder instead of target
    resources:
        static-locations: file:core/src/main/resources/static/ #directly serve from src folder instead of target
        cache:
            period: 0
    mvc:
        static-path-pattern: /static/**

    #Access from http://localhost:8080/h2-console/, db url: jdbc:h2:mem:testdb, username: sa
    h2:
        console:
            enabled: true
    jooq:
        sql-dialect: H2

    elasticsearch:
        rest:
            uris: http://${ELASTICSEARCH_HOSTADDR:localhost:9200}


keycloak:
    realm: blogapp
    auth-server-url: http://localhost:${KEYCLOAK_PORT:8082}/auth/
    ssl-required: external
    resource: gateway-app-client
    public-client: true # for gateway app
    principal-attribute: name
    credentials.secret: dc168f0c-3c7f-47b9-b700-43d746978566

